model:
  layers: 3
  num_K: 7
  hidden_channel: 12
  factor1: 10
  factor2: 10
  crop_size: 192
  clip: 0.01
  head: 4
training:
  epoch: 800
  batch_size: 20
  warmup: 20
  start_lr: 0.0001
  ref_lr: 0.001
  final_lr: 0.0006
  device: "cuda:1"